baseURL = "https://nesu.ca"
languageCode = "en"
title = "Facility Solutions"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true
